print ("\033[1mUNIVERSITAS TIDAR\033[0m")
print ("Universitas Tidar merupakan Perguruan Tinggi Pemerintah atau Perguruan Tinggi Negeri yang telah ditetapkan berdasarkan Peraturan Presiden Republik Indonesia Nomor 23 Tahun 2014 pada tanggal 1 April 2014")
print ("\n\033[1mJURUSAN TEKNIK ELEKTRO, MEKATRONIKA, DAN INFORMASI\033[0m")
print ("Jurusan Teknik Elektro terdiri atas tiga program studi, antara lain:")
print ("  1. S1 Teknik Elektro (\x1b[3mBachelor of Electrical Engineering)")
print ("  2. S1 Teknologi Informasi (\x1b[3mBachelor of Information Technology)")
print ("  3. S1 Teknik Mekatronika (\x1b[3mBachelor of Mechatronics Engineering)")